version: '3.6'

networks:
  guaca_network:
    driver: bridge

services:
  guacd:
    restart: unless-stopped
    container_name: guacd
    image: guacamole/guacd
    networks:
      - guaca_network
    volumes:
      - ./drive:/drive:rw
      - ./record:/record:rw
    ports:
      - 4822

  postgres:
    restart: unless-stopped
    container_name: guaca_postgres
    image: postgres
    networks:
      - guaca_network
    environment:
      - POSTGRES_DB
      - POSTGRES_PASSWORD
      - POSTGRES_USER
    volumes:
      - ./initdb.sql:/docker-entrypoint-initdb.d/dump.sql
    ports:
      - 5432

  guacamole:
    restart: unless-stopped
    networks:
      - guaca_network
    container_name: guacamole
    image: guacamole/guacamole
    depends_on:
      - guacd
      - postgres
    environment:
      - GUACD_HOSTNAME=guacd
      - POSTGRES_HOSTNAME=postgres
      - POSTGRES_DATABASE=$POSTGRES_DB
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - TOTP_ENABLED
      - OTP_ISSUER=Apache Guacamole
      - TOTP_DIGITS=6
      - TOTP_PERIOD=30
      - TOTP_MODE=sha1
    ports:
      - 8080

  nginx:
      restart: unless-stopped
      container_name: guaca_nginx
      image: guaca_nginx
      networks:
        - guaca_network
      build:
        context: nginx
        dockerfile: nginx/Dockerfile
      depends_on:
        - guacamole
      command: [nginx-debug, '-g', 'daemon off;']
      ports:
        - 80:80
