version: '3.6'
services:
  guacd:
    restart: always
    container_name: guacd
    image: guacamole/guacd
    volumes:
      - ./drive:/drive:rw
      - ./record:/record:rw

  postgres:
    restart: always
    container_name: postgres
    image: postgres
    environment:
      - PGDATA=/var/lib/postgresql/data/guacamole
      - POSTGRES_DB
      - POSTGRES_PASSWORD
      - POSTGRES_USER
    volumes:
      - ./init:/docker-entrypoint-initdb.d:ro
      - ./data:/var/lib/postgresql/data:rw
    ports:
      - 5432

  guacamole:
    restart: always
    container_name: guacamole
    image: guacamole/guacamole
    depends_on:
      - guacd
      - postgres
    links:
      - guacd
      - postgres
    environment:
      - GUACD_HOSTNAME=guacd
      - POSTGRES_HOSTNAME=postgres
      - POSTGRES_DATABASE=$POSTGRES_DB
      - POSTGRES_PASSWORD
      - POSTGRES_USER
    ports:
      - 8080/tcp

  nginx:
      container_name: nginx
      image: nginx
      build:
        context: nginx
        dockerfile: Dockerfile
      depends_on:
        - guacamole
      command: [nginx-debug, '-g', 'daemon off;']
      ports:
        - 80:80
